[context]
json_path = "./workspace/764-ef5c5c99/context.json"
result_path = "./workspace/cr_result/764-ef5c5c99"

[project]
language = "TypeScript"
status = "update"
guidelines_path = "./workspace/guidelines_docs/TypeScript.md"
requirements_path = ""

[llm]
model = "openai/claude-opus-4-6"
api_key = "sk-i3Ur1NdTBg4pH0ZI4oy1PeOqX4lOSvPfaVGSvhAgYBrGRHKL"
api_base = "https://infplacex.com/v1"

platform = "gitlab"


